[package]
name = "cpge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
alloc = []
std = ["alloc"]
gl = [
    "std",
    "dep:vulkano", "dep:vulkano-shaders", "dep:tokio",
    # macOS
    "dep:objc2", "dep:objc2-foundation", "dep:objc2-app-kit"
]

[[example]]
name = "simple-ui"
required-features = ["gl"]

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4", optional = true }
objc2-foundation = { version = "0.3.2", optional = true }
objc2-app-kit = { version = "0.3.2", optional = true }

[dependencies]
arrayvec = "0.7.8"
num-traits = "0.2.19"
rust_decimal = { version = "1.42.1", features = ["macros", "maths"] }
vulkano = { version = "0.35.2", optional = true }
vulkano-shaders = { version = "0.35.0", optional = true }
tokio = { version = "1.53.1", optional = true, features = ["full"] }

[build-dependencies]
build-rs = "0.3.5"
cmake = "0.1.58"
walkdir = "2.5.0"
